### ISSUE TITLE
Mystral is trolling me

### ISSUE THREAD

**Issue by ImDxni** [Glyart/Mystral#1]
when i try to set property, it says "they key cannot be empty" even if i insert a corrected key

proofs:
![image](https://user-images.githubusercontent.com/39953274/118537365-28cfbd80-b74d-11eb-9f57-002c12fd7af5.png)
![image](https://user-images.githubusercontent.com/39953274/118537375-2cfbdb00-b74d-11eb-8e84-7714153d0451.png)

**Comment by Valxrie** [comment]
> when i try to set property, it says "they key cannot be empty" even if i insert a corrected key
> 
> proofs:
> ![image](https://user-images.githubusercontent.com/39953274/118537365-28cfbd80-b74d-11eb-9f57-002c12fd7af5.png)
> ![image](https://user-images.githubusercontent.com/39953274/118537375-2cfbdb00-b74d-11eb-8e84-7714153d0451.png)

Problem solved. Get the latest version tag from the README.md file.
