### ISSUE TITLE
ClassCastException on DataSourceUtils#close(DatabaseAccessor)

### ISSUE THREAD

**Issue by ImDxni** [Glyart/Mystral#2]
When i pass the instance of AsyncDatabase to DataSourceUtils#close(DatabaseAccessor) method, it throws ClassCastException:
`com.glyart.mystral.database.AsyncDatabase cannot be cast to com.glyart.mystral.database.DatabaseAccessor
`

**Comment by Valxrie** [comment]
Use 1.2.1 version. This problem has been removed.
